# Generated by Django 5.2.5 on 2025-09-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_estudiante_apellido_alter_estudiante_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('C', 'Casa'), ('M', 'Celular'), ('T', 'Trabajo')], default='C', max_length=1)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='home.estudiante')),
            ],
        ),
    ]
