# Generated by Django 5.2.5 on 2025-09-11 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_autor', to='home.estudiante')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_autorizador', to='home.estudiante')),
            ],
        ),
    ]
